name: Lint script

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'book.json'
      - '.gitignore'
      - 'Dockerfile'
      - 'Dockerfile.*'
      - '.devcontainer/**'
      - '.vscode/**'
      - '.github/**'
      - '!.github/workflows/lint.yml'
      - 'docs/**'
    branches:
      - "main"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint with autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --recursive --in-place --global-config ".pep8" .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Lint script with autopep8
